# Use a base image
FROM alpine

# Example of operations performed as root user (during the build phase)
RUN apk add --no-cache curl wget

# Example of command that could be run as root user
CMD ["sh"]
