### --- Bad Practice 22: Poor documentation of image provenance, misconfigured or missing Docker daemon log level configuration --- ###
version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    command: ["nginx", "-g", "daemon off;"]

  app:
    image: myapp:latest
    ports:
      - "8080:8080"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    command: ["sh", "-c", "echo 'Running app...' && sleep 300"]
