## -- Bad practice 21:  Do not ensure Docker daemon logging level is set to info -- ##
version: '3.8'

services:
  app:
    image: ubuntu:latest
    build:
      context: .
    ports:
      - "80:80"
    environment:
      - DOCKER_OPTS="--log-level debug"
    volumes:
      - .:/app
    command: ["python", "app.py"]
