## -- Bad practice 24: do not sign the Docker image with GPG key -- ##
version: '3'
services:
  web:
    image: python:3.7
    build:
      context: .
      # dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    command: python /app/app.py
