### --- Bad Practice 25: host system directories are mounted on containers --- ###
version: '3'

services:
  app:
    image: ubuntu:latest
    volumes:
      - /etc:/etc
    command: bash
### -------------------------------------------------------------------------- ###