### --- Bad Practice 23 --- ###
version: '3.8'

services:
  web:
    platform: linux/arm64
    image: nginx:latest
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    command: ["nginx", "-g", "daemon off;"]
