### --- Bad Practice 10: data exchanged between containers is NOT encrypted on different nodes on the overlay network --- ###
version: '3'

services:
  app:
    image: ubuntu
    command: bash
