# "bad" practice 12: no specific labels

services:
  web:
    image: ubuntu
    labels:
      - "service=management"
      - "type=HR"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.service == customer
      resources:
        limits:
          memory: 128MB
        reservations:
          memory: 256MB

  app:
    image: ubuntu:latest
    labels:
      - "service=customer"
      - "type=Sales"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.service == management
      resources:
        limits:
          memory: 512MB
        reservations:
          memory: 1GB

  # db:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: app_db
  #   labels:
  #     - "service=management"
  #     - "type=HR"
  #   deploy:
  #     replicas: 3
  #     placement:
  #       constraints:
  #         - node.labels.type == Sales
  #     resources:
  #       limits:
  #         memory: 1GB
  #       reservations:
  #         memory: 2GB

networks:
  default:
    external: true
    name: mynetwork
