# bad practice 19: mount propagation mode set to shared

services:
  web:
    image: ubuntu:latest
    ports:
      - "8080:80"
    volumes:
      - /host/path:/container/path:shared
    environment:
      - ENV_VAR=some_value
    depends_on:
      - database
    restart: always

  database:
    image: ubuntu:latest #mysql:latest
    volumes:
      - /host/mysql:/var/lib/mysql:shared
      - /host/mysql/config:/etc/mysql/conf.d:shared
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always

  # redis:
  #   image: redis:latest
  #   volumes:
  #     - /host/redis:/data:shared
  #   restart: always