### --- Bad Practice 7: do not manage restart policies --- ###
version: '3.8'
services:
  myapp:
    image: ubuntu
    ports:
      - "80:80"
### ------------------------------------------------------ ###
