### --- Bad Practice 13: Do not run as a specific non-root user & Mount the entire host filesystem into the container --- ###
version: '3.8'

services:
  myservice:
    image: myimage:latest
    volumes:
      - /:/host 
    working_dir: /host
    command: ["bash"]