### --- Bad Practice 5: volume not set as read-only --- ###
version: '3.7'
services:
  web:
    image: ubuntu:latest
    ports:
      - "80:80"
    volumes:
      - ./data:/data
### --------------------------------------------------- ###
