FROM python

RUN apt-get update && apt-get install -y \
    nginx=1.20.* \
    curl=7.74.* \
    && rm -rf /var/lib/apt/lists/*

COPY . /app

# Expose port for nginx
EXPOSE 80

# Start nginx with specified configuration and version
CMD ["nginx", "-g", "daemon off;"]
