### --- Good Practice 6: The my_secret secret is defined under the secrets key and refers to the super-secret-data.txt file --- ###
secrets:
  my_secret:
    file: ./super-secret-data.txt

services:
  web:
    image: ubuntu:24.04
    secrets:
      - my_secret
### --------------------------------------------------------------------------------------------------------------------------- ###
