version: '3.8'

## -- Best practice 19: secure deployments -- ##
services:
  myapp:
    image: your-registry.example.com/myapp-web:1.0
    ports:
      - "80:80"
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.example.description=Securely deployed application"
      - "com.example.department=IT"

  nginx:
    image: nginx:1.20
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.example.description=Securely deployed Nginx"
      - "com.example.department=IT"
