services:
  web:
    image: alpine:3.19.0
    container_name: mywebapp
    ports:
      - "8080:8080"  # Best Practice 26: expose only necessary ports
    volumes:
      - ./ubuntu.conf:/etc/ubuntu/ubuntu.conf
