
services:
  web:
    image: alpine:3.19.0
    ulimits:
      nofile:
        soft: 1024
        hard: 2048
      nproc:
        soft: 1000
        hard: 2000
## -- Best practice 31: Set proper ulimits in Docker Compose files -- ##
