### --- Best Practice 25: host system directories are not mounted on containers --- ###

services:
  app:
    image: alpine:3.19.0
    volumes:
      - /app/data:/app/data
    command: bash
### ------------------------------------------------------------------------------ ###