### --- Best Practice 35: Ensure that Docker's default bridge "docker0" is not used --- ###
version: '3'

services:
  app:
    image: ubuntu
    command: bash
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
