# Start with a specific base image
FROM python:3.9-slim

# Metadata indicating image maintainer and source
LABEL maintainer="yourname@example.com"
LABEL source="https://github.com/yourusername/yourproject"

# Install necessary packages with specific versions and sources
RUN apt-get update && apt-get install -y \
    nginx=1.20.* \
    curl=7.74.* \
    && rm -rf /var/lib/apt/lists/*

# Copy application code with clear indication of its origin and version
COPY . /app

# Expose port for nginx
EXPOSE 80

# Start nginx with specified configuration and version
CMD ["nginx", "-g", "daemon off;"]

## -- Best practice 23: software Bill of Materials (SBOM) metadata -- ##
LABEL sbom='{"image": {"name": "myapp-web", "version": "1.0"}, "components": [{"name": "python", "version": "3.9.7", "license": "PSF", "source": "https://www.python.org/"}, {"name": "nginx", "version": "1.20.1", "license": "BSD-2-Clause", "source": "https://nginx.org/"}, {"name": "curl", "version": "7.74.0", "license": "MIT", "source": "https://curl.se/"}, {"name": "Flask", "version": "2.0.1", "license": "BSD-3-Clause", "source": "https://pypi.org/project/Flask/"}, {"name": "requests
