# Use a secure base image for building
FROM python:3.9-slim

# Metadata indicating image maintainer and source
LABEL maintainer="yourname@example.com"
LABEL source="https://github.com/yourusername/yourproject"

# Install necessary packages
RUN apt-get update && apt-get install -y \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

# Copy application code
COPY . /app

# Expose port for application
EXPOSE 80

## -- Best practice 24: sign the Docker image with GPG key -- ##
RUN gpg --import /path/to/your/private/key.asc
RUN gpg --output /app/image.sig --detach-sig /app/Dockerfile

# Start the application
CMD ["python", "app.py"]
