services:
  app1:
    image: alpine:3.19.0
    networks:
      - app1_net

  app2:
    image: alpine:3.19.0
    networks:
      - app2_net

  app3:
    image: alpine:3.19.0
    networks:
      - app3_net

## -- Best practice 2: be mindful of inter-container connectivity -- ##
networks:
  app1_net:
    # internal: false
    driver: bridge

  app2_net:
    # internal: false
    driver: bridge

  app3_net:
    # internal: false
    driver: bridge
