version: '3.8'

services:
  app:
    image: alpine
    command: ["sh", "-c", "while true; do echo Hello; sleep 3600; done"]
    security_opt:
      - "seccomp=/path/to/seccomp-profile.json"
## -- Best practice 14 : Use seccomp profiles to restrict available syscalls -- ##
# Path: good_seccomp-profile14.json
#{
#  "defaultAction": "SCMP_ACT_ALLOW",
#  "architectures": [
#    "SCMP_ARCH_X86_64"
#  ],
#  "syscalls": [
#    {
#      "names": [
#	"write"
#      ],
#      "action": "SCMP_ACT_ERRNO"
#    }
#  ]
#}
