### --- Best Practice 5: Appending :ro to the end of the volume specifies that the volume is mounted read-only --- ###
services:
  web:
    image: alpine:3.19.0
    ports:
      - "80:80"
    volumes:
      - ./data:/data:ro
### -------------------------------------------------------------------------------------------------------------- ###
