### --- Best Practice 27: limit memory usage --- ###

services:
  web:
    image: alpine:3.19.0
    container_name: mywebapp
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          memory: 256M
### -------------------------------------------- ###