### --- Best Practice 0: limit capabilities --- ###

services:
  example_service:
    image: alpine:3.19.0  # Specify the image to use
    cap_drop:
      - ALL  # Drop all capabilities
    cap_add:
      - CHOWN  # Add the necessary capabilities for the service to run
    security_opt:
      - no-new-privileges:true  # Prevents escalation of privilege
