## -- Best practice 20: using a trusted registry with strict access controls to store the Docker image and SBOM file -- ##

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: alpine:3.19.0 # or your-registry.example.com/myapp-web:1.0
    container_name: myapp_container
    ports:
      - "80:80"
    environment:
      - GPG_KEY_PATH=/path/to/your/private/key.asc
    volumes:
      - ./app:/app