## -- Best practice 17: pin versions -- ##

services:
  web:
    image: mariadb:10.6.15 # Pinned to a specific version
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - frontend
    restart: always

  app:
    image: mariadb:10.6.15 #lscr.io/linuxserver/mariadb:latest  # Pinned to a specific version
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - frontend
      - backend
    depends_on:
      - db
    restart: on-failure

  db:
    image: mariadb:10.6.15 #arm64v8/mariadb:10.6.15
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

volumes:
  db_data:

networks:
  frontend:
  backend: