services:
  myapp:
    image: alpine:3.19.0
    cap_drop:
      - ALL  # Removes all abilities
    cap_add:
      - NET_ADMIN  # Add only necessary NET_ADMIN capacity
    security_opt:
      - no-new-privileges:true  # Prevents escalation of privilege
