### --- Best Practice 16: Ensure network traffic is restricted between containers on the default bridge --- ###
# Web and db containers use separate networks (frontend and backend), so they cannot communicate directly with each other. 
# Only containers in the same network can communicate with each other.

services:
  web:
    image: alpine:3.19.0
    ports:
      - "80:80"
    networks:
      - frontend

  db:
    image: alpine:3.19.0
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
### ------------------------------------------------------------------------------------------------------- ###