### --- Best Practice 35: Ensure that Docker's default bridge "docker0" is not used --- ###

services:
  app:
    image: alpine:3.19.0
    command: bash
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
