## -- Best practice 22: documenting image provenance effectively -- ##

services:
  app:
    image: alpine:3.19.0 # or myorg/myapp:1.0.0
    container_name: my_app_container
    labels:
      org.opencontainers.image.created: "2024-08-17T10:00:00Z"
      org.opencontainers.image.authors: "Dev Team <devteam@myorg.com>"
      org.opencontainers.image.version: "1.0.0"
      org.opencontainers.image.revision: "abc123def456"
      org.opencontainers.image.source: "https://github.com/myorg/myapp"
      org.opencontainers.image.licenses: "MIT"
      org.opencontainers.image.documentation: "https://docs.myorg.com/myapp"
      org.opencontainers.image.base.name: "node:14-alpine"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/src/app
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  # db:
  #   image: postgres:13.3
  #   container_name: my_db_container
  #   labels:
  #     org.opencontainers.image.created: "2024-08-10T10:00:00Z"
  #     org.opencontainers.image.authors: "DB Admin <dbadmin@myorg.com>"
  #     org.opencontainers.image.version: "13.3"
  #     org.opencontainers.image.revision: "def789ghi012"
  #     org.opencontainers.image.source: "https://github.com/postgres/postgres"
  #     org.opencontainers.image.licenses: "PostgreSQL"
  #     org.opencontainers.image.documentation: "https://www.postgresql.org/docs/13/"
  #     org.opencontainers.image.base.name: "postgres:13.3"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: exampleuser
  #     POSTGRES_PASSWORD: examplepass

volumes:
  db_data: