services:
  my-application:
    image: alpine:3.19.0 
    ports:
      - "8080:80"
    deploy:
      resources:
        reservations:
## -- Best practice 21: requesting resource limits -- ##
          cpus: '0.5'  # Request 0.5 CPU cores
          memory: '256M'  # Request 256MB memory
        limits:
          cpus: '1.0'  # Limit to 1 CPU core
          memory: '512M'  # Limit memory to 512MB
## -------------------------------------------------- ##
