version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: mywebapp
    ports:
      - "8080:8080"  # Best Practice 26: expose only necessary ports
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
