### --- Bad Practice 25: host system directories are not mounted on containers --- ###
version: '3'

services:
  app:
    image: ubuntu:latest
    volumes:
      - /app/data:/app/data
    command: bash
### ------------------------------------------------------------------------------ ###