### --- Best Practice 3: limit on number of processes --- ###
services:
  web_server:
    image: ubuntu:22.04
    ulimits:
      nproc: 50
      
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
### ------------------------------------------------------- ###
